// Empty defaults — all categories and items come from server for the active cafe
export const FALLBACK_CATEGORIES = [];
export const FALLBACK_PRODUCTS = [];

// Bilingual vocabulary mappings
export const VOCAB = {
  en: {
    addCustomer: "Add Customer",
    table: "Table",
    dineIn: "Local (Dine-in)",
    taxes: "Taxes (15% VAT)",
    total: "Total",
    addDish: "Add Custom Dish",
    pay: "Pay Order",
    searchPlaceholder: "Search in products...",
    back: "Back",
    clearCart: "Void Order",
    print: "Print",
    kitchen: "Kitchen",
    activity: "Activity",
    discount: "Discount",
    notes: "Notes",
    disable: "Void",
    more: "More",
    home: "Home",
    orders: "Orders",
    tables: "Tables",
    new: "New",
    cancel: "Cancel",
    confirm: "Confirm",
    tableSelection: "Table Selection",
    custName: "Customer Name",
    successMsg: "Order placed successfully!",
    allOrders: "All Orders",
    uncompletedOrders: "Active Orders",
    complete: "Complete",
    completed: "Completed",
    active: "Active",
    paymentMethods: "Payment Methods",
    paymentDevice: "Payment Device",
    disconnected: "Disconnected",
    cash: "Cash",
    network: "Network / Card",
    remainingToPay: "Remaining to Pay",
    customer: "Customer",
    currency: "Currency",
    manual: "Manual",
    payText: "Pay",
    exactAmount: "Exact Amount",
    customAmount: "Custom Amount",
    amountToPay: "Amount to Pay",
    fullyCovered: "Fully Covered",
    paidAmount: "Paid",
    pleaseCoverRemaining: "Please cover the remaining amount with Cash or Card before paying."
  },
  ar: {
    addCustomer: "إضافة عميل",
    table: "طاولة",
    dineIn: "محلي",
    taxes: "الضرائب (15%)",
    total: "الإجمالي",
    addDish: "إضافة طبق",
    pay: "دفع الطلب",
    searchPlaceholder: "البحث في المنتجات",
    back: "الرجوع",
    clearCart: "إلغاء الطلب",
    print: "طباعة",
    kitchen: "المطبخ",
    activity: "نشاط",
    discount: "خصم",
    notes: "ملاحظات",
    disable: "تعطيل",
    more: "المزيد",
    home: "الرئيسية",
    orders: "الطلبات",
    tables: "الطاولات",
    new: "جديد",
    cancel: "إلغاء",
    confirm: "تأكيد",
    tableSelection: "تحديد الطاولة",
    custName: "اسم العميل",
    successMsg: "تم إرسال الطلب بنجاح!",
    allOrders: "كل الطلبات",
    uncompletedOrders: "الطلبات النشطة",
    complete: "إكمال",
    completed: "مكتمل",
    active: "نشط",
    paymentMethods: "طرق الدفع",
    paymentDevice: "جهاز الدفع",
    disconnected: "غير متصل",
    cash: "Cash",
    network: "شبكة",
    remainingToPay: "المتبقي للدفع",
    customer: "العميل",
    currency: "العملة",
    manual: "يدوي",
    payText: "دفع",
    exactAmount: "المبلغ المتبقي بالضبط",
    customAmount: "مبلغ مخصص",
    amountToPay: "المبلغ المراد دفعه",
    fullyCovered: "تم تغطية كامل المبلغ",
    paidAmount: "مدفوع",
    pleaseCoverRemaining: "يرجى تغطية المبلغ المتبقي بالكاش أو الشبكة قبل إتمام الدفع."
  }
};
