// High-fidelity categories matching the reference picture exactly
export const FALLBACK_CATEGORIES = [
  { id: "sweets", nameEn: "Sweets", nameAr: "الحلويات" },
  { id: "cold_coffee", nameEn: "Cold Coffee", nameAr: "القهوة الباردة" },
  { id: "hot_coffee", nameEn: "Hot Coffee", nameAr: "القهوة الساخنة" },
  { id: "cake_share", nameEn: "Cake Share", nameAr: "كيك شير" },
  { id: "breakfast", nameEn: "Breakfast", nameAr: "فطور" },
  { id: "juice", nameEn: "Juice", nameAr: "عصيرات" },
  { id: "cold_drinks", nameEn: "Cold Drinks", nameAr: "المشروبات الباردة" },
  { id: "turkish_coffee", nameEn: "Turkish Coffee", nameAr: "القهوة التركية" },
  { id: "tea", nameEn: "Tea", nameAr: "الشاي" },
  { id: "saudi_coffee", nameEn: "Saudi Coffee", nameAr: "القهوة السعودية" },
  { id: "cake", nameEn: "Cake", nameAr: "الكيك" },
  { id: "dessert", nameEn: "Dessert", nameAr: "الحلا" },
  { id: "party", nameEn: "Party", nameAr: "حفلات" },
  { id: "snacks", nameEn: "Snacks", nameAr: "وجبات خفيفة" },
  { id: "ice_cream", nameEn: "Ice Cream", nameAr: "آيس كريم" }
];

// Fallback products matching categories
export const FALLBACK_PRODUCTS = [
  { id: "p1", categoryId: "hot_coffee", nameEn: "V60 Hot", nameAr: "V60 حار", price: 19.0 },
  { id: "p2", categoryId: "hot_coffee", nameEn: "Flat White", nameAr: "فلات وايت", price: 16.0 },
  { id: "p3", categoryId: "hot_coffee", nameEn: "Cortado", nameAr: "كورتادو", price: 14.0 },
  { id: "p4", categoryId: "cold_coffee", nameEn: "Iced Spanish Latte", nameAr: "سبانش لاتيه بارد", price: 22.0 },
  { id: "p5", categoryId: "cold_coffee", nameEn: "Iced Americano", nameAr: "أمريكانو بارد", price: 14.0 },
  { id: "p6", categoryId: "saudi_coffee", nameEn: "Saudi Dallah Small", nameAr: "دلة سعودية صغيرة", price: 25.0 },
  { id: "p7", categoryId: "saudi_coffee", nameEn: "Saudi Dallah Large", nameAr: "دلة سعودية كبيرة", price: 40.0 },
  { id: "p8", categoryId: "breakfast", nameEn: "Halloumi Wrap", nameAr: "ساندوتش حلومي", price: 18.0 },
  { id: "p9", categoryId: "breakfast", nameEn: "Pancakes Maple", nameAr: "بان كيك عسل", price: 22.0 },
  { id: "p10", categoryId: "tea", nameEn: "Red Tea", nameAr: "كوب شاي أحمر", price: 6.0 },
  { id: "p11", categoryId: "tea", nameEn: "Karak Pot", nameAr: "شاي كرك دلة", price: 18.0 },
  { id: "p12", categoryId: "dessert", nameEn: "Saffron Cake", nameAr: "كيكة الزعفران", price: 24.0 },
  { id: "p13", categoryId: "dessert", nameEn: "San Sebastian", nameAr: "سان سيباستيان", price: 28.0 }
];

// Bilingual vocabulary mappings
export const VOCAB = {
  en: {
    addCustomer: "Add Customer",
    table: "Table",
    dineIn: "Local (Dine-in)",
    taxes: "Taxes (15% VAT)",
    total: "Total",
    addDish: "Add Custom Dish",
    pay: "Pay Order",
    searchPlaceholder: "Search in products...",
    back: "Back",
    clearCart: "Void Order",
    print: "Print",
    kitchen: "Kitchen",
    activity: "Activity",
    discount: "Discount",
    notes: "Notes",
    disable: "Void",
    more: "More",
    home: "Home",
    orders: "Orders",
    tables: "Tables",
    new: "New",
    cancel: "Cancel",
    confirm: "Confirm",
    tableSelection: "Table Selection",
    custName: "Customer Name",
    successMsg: "Order placed successfully!",
    allOrders: "All Orders",
    uncompletedOrders: "Active Orders",
    complete: "Complete",
    completed: "Completed",
    active: "Active"
  },
  ar: {
    addCustomer: "إضافة عميل",
    table: "طاولة",
    dineIn: "محلي",
    taxes: "الضرائب (15%)",
    total: "الإجمالي",
    addDish: "إضافة طبق",
    pay: "دفع الطلب",
    searchPlaceholder: "البحث في المنتجات",
    back: "الرجوع",
    clearCart: "إلغاء الطلب",
    print: "طباعة",
    kitchen: "المطبخ",
    activity: "نشاط",
    discount: "خصم",
    notes: "ملاحظات",
    disable: "تعطيل",
    more: "المزيد",
    home: "الرئيسية",
    orders: "الطلبات",
    tables: "الطاولات",
    new: "جديد",
    cancel: "إلغاء",
    confirm: "تأكيد",
    tableSelection: "تحديد الطاولة",
    custName: "اسم العميل",
    successMsg: "تم إرسال الطلب بنجاح!",
    allOrders: "كل الطلبات",
    uncompletedOrders: "الطلبات النشطة",
    complete: "إكمال",
    completed: "مكتمل",
    active: "نشط"
  }
};
